name: Update run_forecast

on:
  workflow_dispatch:
  schedule:
    - cron: "10 * * * *"

permissions:
  contents: write

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install "numpy<2" 
          pip install pandas requests h5py 
          pip install tensorflow==2.10.*

      - name: Run forecast script
        run: |
          python scripts/run_forecast.py

      - name: Commit updated forecast files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/forecast.json
          git add data/input_latest_3days.csv
          git add data/latest_inputs.json

          git commit -m "Update forecast data" || echo "No changes"

          git push
